Some improvements for plasma-drawer
P-Connor/plasma-drawer pull request #48
Opened 2023-02-25 17:34 UTC by appleneko2001

In this PR will improve plasma-drawer for a bit. You can use mouse back button to navigate to previous level of view or close drawer, if you are on main level of drawer. Also I added an option to allow you adjust text size of label of all application entry (including grid view and search result list item) to make them more easily to read.
### added features:
+ Use Mouse Back button (side button usually) to navigate back or close drawer easily.
+ Adjustable label text point size (Grid item and List item while in search state), uses `font.pointSize` [Qt Docs](https://doc.qt.io/qt-5/qml-qtquick-text.html#font.pointSize-prop). Its able to change in "Configure Plasma Drawer" -> "Label size of application entry (point size)". Default value is `12`.

Tested on Debian bookworm, KDE Plasma 5.26.90, KDE Framework 5.103.0, Qt 5.15.8.

### Screenshots (12 point size of text, 1920x1080)
![Screenshot_20230226_021849](https://user-images.githubusercontent.com/38249047/221370877-180b4335-71a8-4d43-a42e-2ebdf5602fa1.png)
![Screenshot_20230226_022100](https://user-images.githubusercontent.com/38249047/221370871-6e45ccd9-07c2-453f-a9f3-e3f87cbdcb78.png)
![Screenshot_20230226_021905](https://user-images.githubusercontent.com/38249047/221370876-a20be13f-bb26-465d-9f79-a88e804276eb.png)

### Screenshots (16 point size of text, 1920x1080)
![Screenshot_20230226_021918](https://user-images.githubusercontent.com/38249047/221370919-f73aa38b-5a5c-4021-9c32-4155c00dde41.png)
![Screenshot_20230226_022044](https://user-images.githubusercontent.com/38249047/221370914-a1bd9ea6-5ac0-4ab9-93bc-37a8e294846f.png)
![Screenshot_20230226_021925](https://user-images.githubusercontent.com/38249047/221370916-b79f1848-ec81-40ae-a71e-bd46e85c0e1b.png)

Lacks on my knowledge of Qt Quick development skills, I can't solve some open issues at this moment. I use this plugin every day and its useful to me. I want to improve it to make it stronger than before. Any suggestions is allowed.

2023-03-08 18:31 UTC, P-Connor requested changes
Overall I like the idea of the changes, but the font size not matching the system font size by default is a dealbreaker. This requires that users configure the widget, and breaks the philosophy that things should work well by default. I think a different approach is needed here.

I noticed on your fork description that you primary wanted to push these changes because Discover was automatically updating your custom version. You should be able to prevent this by changing the Id in the metadata.json file

2023-03-08 18:31 UTC, P-Connor commented on contents/ui/ConfigGeneral.qml
> +    property alias cfg_appLabelPointSize:       appLabelPointSize.value
I like the idea of a configurable font size, but one consequence of this is that the font size no longer matches the user's system font size by default. This requires that if the system font size is not the configuration default (12 as you've specified here), they will have to change this value manually when they install the widget or every time they change the system font size. If we want to add a font size config option, we should definitely maintain the system font size as a default

2023-03-08 18:31 UTC, P-Connor commented on contents/config/main.xml
> +    <entry name="appLabelPointSize" type="Double">
I think this could be renamed to something more generic like "fontPointSize", since it applies not just to the app labels but also to the search results

2023-03-08 18:31 UTC, P-Connor commented on contents/ui/ConfigGeneral.qml
> +    RowLayout {
This spinbox could probably be moved to the General section if the config option is changed to a general font point size instead of app label point size

2023-03-08 18:31 UTC, P-Connor commented on contents/ui/MenuRepresentation.qml
> +        if(searchField.text != ""){
I'd do `if (!searching) {` instead here

2023-03-08 18:31 UTC, P-Connor commented on contents/ui/ItemListDelegate.qml
> +        font.pointSize: plasmoid.configuration.appLabelPointSize
I think if we're changing the font size here, we should make sure that it is updated everywhere else in the widget. The searchField in MenuRepresentation and the runner results section headers / show more button should also be changed in my opinion

2023-03-08 18:31 UTC, P-Connor commented on contents/ui/MenuRepresentation.qml
> +    function handleBackButton() {
Maybe we could just call this method 'back()' to match the style of the other methods and make it more generic if we ever want to trigger this functionality with another button

2023-03-10 09:19 UTC, appleneko2001 commented on contents/ui/ConfigGeneral.qml
> +    property alias cfg_appLabelPointSize:       appLabelPointSize.value
ok I do some changes here, if there is any related api exists to get system font size

2023-03-10 09:57 UTC, appleneko2001 commented
Hi! I'll push changes later

2023-03-11 11:16 UTC, appleneko2001 commented
nah its different branch, i have to redo changes on same branch or it just break something

2023-03-11 11:16 UTC, closed without merging